### ISSUE TITLE
Where are Depth Images?

### ISSUE THREAD

**Issue by oreo-lp** [lifelong-robotic-vision/OpenLORIS-Object#4]
I have downloaded the [test dataset](https://drive.google.com/file/d/1J7_ljcwSZNXo6KwlhRZoG0kiEcRK7U6x/view?usp=sharing), but dataset does not include depth images.

**Comment by oreo-lp** [comment]
Does this dataset not include depth images?

**Comment by oreo-lp** [comment]
I have download the datasets from this link: [download link](https://docs.google.com/document/d/1KlgjTIsMD5QRjmJhLxK4tSHIr0wo9U6XI5PuF8JDJCo/edit)

**Comment by oreo-lp** [comment]
I would really appreciate if you could help me solve this issue. @sheqi @ffeng1996

**Comment by ffeng1996** [comment]
Hi, 
Thanks for your interest. The link below please find the depth images. Please note that this link only contains the depth images for the 1-st version data. The updated version will be released soon.

Link: https://pan.baidu.com/s/1fQeNcZruTuz2xZ4s6SLOBQ  password:l3mn

**Comment by oreo-lp** [comment]
thank you very much !!

**Comment by ffeng1996** [comment]
Always welcome. I am going to close this issue and please feel free (email: ffeng1017@gmail.com) to contact me if you encounter any further problems:)

**Comment by oreo-lp** [comment]
thank you!
